### ISSUE TITLE
Improper Unicode Support

### ISSUE THREAD

**Issue by Mehdical-Man** [ThioJoe/F-Key-Sender#6] opened 2024-09-25 19:51 UTC
## 1. Unicode code points between U+100000 and U+10FFFF are incorrectly recognised as invalid
The Unicode standard encodes from `U+0000` to `U+10FFFF` not `U+0000` to `U+FFFFF`. 

## 2. Even-numbered non-BMP Unicode planes are treated as odd
For example: Sending a Unicode codepoint between `U+20000` ­– `U+2FFFF` send characters between `U+10000` (󐀀) – `U+1FFFF` (🿿). Sending `U+10000` – `U+1FFFF`  send the correct characters.

### The same problem also occurs with these ranges:

`U+40000`–`U+4FFFF`, `U+60000`–`U+6FFFF`, `U+80000`–`U+8FFFF`, `U+A0000`–`U+AFFFF`, `U+C0000`–`U+CFFFF`, `U+E0000`–`U+EFFFF`
### They’re treated as:
`U+30000`–`U+3FFFF`, `U+50000`–`U+5FFFF`, `U+70000`–`U+7FFFF`, `U+90000`–`U+9FFFF`, `U+B0000`–`U+BFFFF`, `U+D0000`–`U+DFFFF`

**Comment by ThioJoe** [comment] 2024-09-26 00:39
Ok the first one at least should be fixed in the new release, 1.1.2. 

The problem was basically this line:
`string utf16String = char.ConvertFromUtf32(codePoint);`

The program was already splitting the larger codepoints into their surrogate pairs, but that built in method to convert to UTF16 doesn't support the surrogate pair range so it was throwing errors. I made a new function that does the conversion manually.

Also this means you can send individual surrogate pair codepoints by themselves if you wanted such as `U+D801` which also would have crashed the previous version.


---

As for the 2nd problem, I can't seem to reproduce even on the previous 1.1.1 version. 

I'm using [this site](https://apps.timwhitlock.info/unicode/inspect) to test it. If I put this in the text box for example: `U+20000` or even just `20000`, it indeed outputs the "𠀀" character with code 20000.

Is the problem just for a specific program or something?

**Comment by Mehdical-Man** [comment] 2024-09-26 15:13
Problem №2 happens in specific software, like Python IDLE. I doubt that F Key Sender is the problem.

**Comment by ThioJoe** [comment] 2024-09-26 16:56
Ah ok i'll just close this as completed then

**Closed as completed by ThioJoe** 2024-09-26 16:56 UTC
